services:
  db:
    image: mysql:8.0.43
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - f1-visualizer-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: ./milestone-0/dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MYSQL_HOST: db
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python setup_db.py &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
volumes:
  f1-visualizer-data:
