FROM node:22-alpine

WORKDIR /app

COPY ./final/frontend/package.json ./final/frontend/package-lock.json ./

RUN npm ci

COPY ./final/frontend .

EXPOSE 5173

ENV VITE_BACKEND_URL=http://backend:8000

CMD ["npm", "run", "dev"]