FROM node:22-alpine

WORKDIR /app

COPY ./milestone-1/frontend/package.json ./milestone-1/frontend/package-lock.json ./

RUN npm ci

COPY ./milestone-1/frontend .

EXPOSE 5173

CMD ["npm", "run", "dev"]